TGP-1455: Update record check your answers
hmrc/trader-goods-profiles-frontend pull request #188
Opened 2024-07-03 19:40 UTC by besscerule

2024-07-04 12:56 UTC, liandra-giacomine commented on app/navigation/Navigator.scala
> +    case p: TraderReferencePage      => _ => routes.UseTraderReferenceController.onPageLoad(NormalMode)
what's this p: thing about? :D

2024-07-04 12:57 UTC, liandra-giacomine commented on app/navigation/Navigator.scala
> +    case p: TraderReferencePage      => _ => routes.UseTraderReferenceController.onPageLoad(NormalMode)
Ah I see it's used in some cases but not in these

2024-07-04 12:57 UTC, liandra-giacomine commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
why are we defaulting the string here?

2024-07-04 13:56 UTC, besscerule commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
because it needs to be explicit, scala doesn't let you default it in the controller onPageLoad unfortunately

2024-07-04 15:22 UTC, AmarkumarJagtap commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
just thinking do we need to even pass recordId as parameter in here, and may be create separate onLoad and OnSubmit for create and update? something like this https://github.com/hmrc/trader-goods-profiles-frontend/blob/main/app/controllers/HasCorrectGoodsController.scala

2024-07-04 16:00 UTC, ChrisCookOC commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
Think I'd lean towards having a version that doesn't take in RecordId and one that does, rather than hardcoding a dummy one

2024-07-05 08:52 UTC, liandra-giacomine commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
Yeah I don't see why we are passing a record Id to the create journey?

2024-07-05 08:56 UTC, liandra-giacomine commented on conf/app.routes
> +GET         /create-record/commodity-code                                                   controllers.CommodityCodeController.onPageLoad(mode: Mode = NormalMode, recordId: String = "new-record")
I see what Beth has done here, she's reusing the page components - which is okay but instead of a default string, it should be optional.

2024-07-05 15:48 UTC, liandra-giacomine requested changes, later dismissed
Refactored in another PR as we don't want to use query params here

2024-07-08 14:38 UTC, ChrisCookOC approved these changes

2024-07-08 14:38 UTC, ChrisCookOC commented on app/navigation/Navigator.scala
> +        println("going to has goods")
println :)

2024-07-08 14:58 UTC, merged