Tgp 474/create remove nirms/niphl page
hmrc/trader-goods-profiles-frontend pull request #216
Opened 2024-07-10 17:08 UTC by omotrium

2024-07-10 20:56 UTC, besscerule requested changes
Virtually perfect :)

At some point we will need to update the data store with the new data - i think this will probably be on Submit of your two controllers if the user answers Yes - however I think that is part of the validate or navigation ticket so it doesn't need to be included in this ticket

2024-07-10 20:56 UTC, besscerule commented on app/viewmodels/checkAnswers/HasNiphlsChangeSummary.scala
> +/*
we don't need this page as it is never seen in a CYA page

2024-07-10 20:56 UTC, besscerule commented on app/viewmodels/checkAnswers/HasNirmsChangeSummary.scala
> +/*
see above

2024-07-10 20:56 UTC, besscerule commented on conf/app.routes
> +GET        /changeHasNirmsChange                                                            controllers.HasNirmsChangeController.onPageLoad(mode: Mode = CheckMode)
in both cases we don't need the CheckMode version of these routes as we never view them from a CYA perspective we always go straight through the journey, so I would remove the CheckMode routes and then also remove the 'mode' parameters for both of the controllers as they are not needed

2024-07-10 20:56 UTC, besscerule commented on conf/messages.en
> +hasNiphlsChange.checkYourAnswersLabel = hasNiphlsChange
this line isn't needed

2024-07-10 20:56 UTC, besscerule commented on conf/messages.en
> +hasNiphlsChange.change.hidden = HasNiphlsChange
this line isn't needed

2024-07-10 20:56 UTC, besscerule commented on conf/messages.en
> +hasNirmsChange.checkYourAnswersLabel = hasNirmsChange
this line isn't needed

2024-07-11 08:36 UTC, vinoocs commented on app/views/HasNiphlsChangeView.scala.html
> +        <div class="govuk-warning-text">
can use the warning components as in the other PR https://github.com/hmrc/trader-goods-profiles-frontend/pull/214/files

2024-07-11 11:26 UTC, besscerule approved these changes

2024-07-11 11:48 UTC, vinoocs approved these changes

2024-07-11 11:50 UTC, merged