Nirms Question and Nirms Number
hmrc/trader-goods-profiles-frontend pull request #44
Opened 2024-05-10 15:25 UTC by mycp98

So far just completed Nirms Question view

2024-05-10 15:54 UTC, yohan-oc approved these changes, later dismissed

2024-05-10 16:02 UTC, liandra-giacomine commented on app/views/NirmsNumberView.scala.html
> +    @formHelper(action = routes.NirmsNumberController.onSubmit(mode), Symbol("autoComplete") -> "off") {
What does setting autoComplete to off do? Could it be useful for accessibilty to have it turned on?

2024-05-13 07:36 UTC, besscerule requested changes

2024-05-13 07:36 UTC, besscerule commented on app/views/HasNirmsView.scala.html
> +        @Html(messages("hasNirms.p2", link(messages("hasNirms.p2.linkText"),
do we want to be using the link component? I think this was the one Nick specifically warned against

2024-05-13 07:36 UTC, besscerule commented on app/views/HasNirmsView.scala.html
> +                legend = Legend(content = "hasNirms.h1", classes = "govuk-visually-hidden")
why the change?

2024-05-13 07:36 UTC, besscerule commented on app/views/NirmsNumberView.scala.html
> +    showBackLink = true
this defaults to true so this line isn't needed

2024-05-13 07:36 UTC, besscerule commented on app/views/components/Link.scala.html
> +@*
i would try not to use this

2024-05-13 09:03 UTC, besscerule approved these changes

2024-05-13 09:31 UTC, ChrisCookOC approved these changes

2024-05-13 09:33 UTC, merged