TGP-2867: Updates for PUT Update Record URL in router
hmrc/trader-goods-profiles-frontend pull request #573
Opened 2024-11-18 14:47 UTC by kenneth-rayner

# Checklist for developers before reviewing
 - [ ] I have merged in main
 - [ ] I have assigned the PR to me
 - [ ] I ran the code with a clean compile test and ensured there are no warnings or deprecations
 - [ ] I have run `sbt prePR` to run all tests, format and check the code coverage
 - [ ] I have written unit tests to cover any code that I wrote, where necessary
 - [ ] I have linked tickets to any TODOs I have written
 - [ ] I have run the microservices with the latest SM2 config
 - [ ] I have checked all the Acceptance Criteria pass
 - [ ] I have run the pipeline journey tests
 - [ ] I have run the local journey tests
 - [ ] I have spoken to the QAs about any changes that may need to be made to the journey tests OR no changes to the journey tests are necessary
 - [ ] I have moved the ticket to Review in Jira
 - [ ] I have left a message in tgp-prs on slack to alert other Devs that this ticket is ready for review
 - [ ] I have checked my PR is not in draft mode

# Checklist for reviewer 1
- [ ] I have added an emoji to the relevant message in tgp-prs to show I am reviewing
- [ ] I have checked out the branch
- [ ] I have run the microservices with the latest SM2 config
- [ ] I have checked all the Acceptance Criteria pass
- [ ] I reviewed the code and left comments where necessary
- [ ] I have left a message on the relevant tgp-prs message to show that I have finished reviewing

# Checklist for reviewer 2
- [ ] I have added an emoji to the relevant message in tgp-prs to show I am reviewing
- [ ] I have checked out the branch
- [ ] I have run the microservices with the latest SM2 config
- [ ] I have checked all the Acceptance Criteria pass
- [ ] I reviewed the code and left comments where necessary
- [ ] I have left a message on the relevant tgp-prs message to show that I have finished reviewing

# Checklist for developers before merging
 - [ ] The PR has been approved by 2 other developers
 - [ ] I have merged in main
 - [ ] I have run `sbt preMerge` to run all tests, check formatting and code coverage
 - [ ] I have run the microservices with the latest SM2 config
 - [ ] I have checked all the Acceptance Criteria pass
 - [ ] I have checked that the QAs have merged in any changes to the journey tests
 - [ ] I have run the pipeline journey tests
 - [ ] I have run the local journey tests

# Reminders for developers after merging
 1. Wait for pipeline to pass
 2. Move ticket to QA column in Jira
 3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

2024-11-19 16:39 UTC, besscerule approved these changes

2024-11-19 16:39 UTC, besscerule commented on app/controllers/goodsRecord/CyaUpdateRecordController.scala
> +      goodsRecordConnector.putGoodsRecord(putRecordRequest, newUpdateGoodsRecord.recordId)
i feel like maybe we could combine these two funcs for readability since they are virtually the same - just an idea

2024-11-20 09:02 UTC, taylors-version requested changes

2024-11-20 09:02 UTC, taylors-version commented on app/connectors/GoodsRecordConnector.scala
> -    // TODO: remove this flag when EIS has implemented the PATCH method - TGP-2417 and keep the put call as default
This section will need pulling back until the router PUT method is available in prod

2024-11-20 09:02 UTC, taylors-version commented on app/connectors/GoodsRecordConnector.scala
> -    // TODO: remove this flag when EIS has implemented the PATCH method - TGP-2417 and keep the put call as default
Same as above

2024-11-20 09:02 UTC, taylors-version commented on app/controllers/goodsRecord/CyaUpdateRecordController.scala
> +      goodsRecordConnector.patchGoodsRecord(
This can stay though as the old updateGoodsRecord is the same as the new patchGoodsRecord and the router will determine where that goes to in EIS

2024-11-20 13:59 UTC, closed without merging