TGP-457 - add homepage and cya redirects to homepage
hmrc/trader-goods-profiles-frontend pull request #60
Opened 2024-05-14 11:51 UTC by ChrisCookOC

2024-05-14 12:07 UTC, liandra-giacomine commented on app/controllers/CheckYourAnswersController.scala
> +        routerConnector.submitTraderProfile(model, request.eori).map { _ =>
we're not handling a failed future here

2024-05-14 12:11 UTC, liandra-giacomine approved these changes
can we also create a PR to update app-config-base?

2024-05-14 12:16 UTC, liandra-giacomine requested changes
Can we add a test case for when the connector call fails?

2024-05-14 13:40 UTC, ChrisCookOC commented
> can we also create a PR to update app-config-base?

What do we need to update there?

2024-05-14 13:40 UTC, ChrisCookOC commented
> Can we add a test case for when the connector call fails?

Added

2024-05-14 13:41 UTC, Ewan-James-Donovan submitted a review, later dismissed

2024-05-15 09:54 UTC, ChrisCookOC commented
> > can we also create a PR to update app-config-base?
> 
> What do we need to update there?

Done and merged :)

2024-05-15 10:08 UTC, liandra-giacomine approved these changes

2024-05-15 10:09 UTC, Ewan-James-Donovan approved these changes

2024-05-15 10:13 UTC, mycp98 approved these changes

2024-05-15 10:14 UTC, merged

2024-05-15 10:14 UTC, besscerule approved these changes

2024-05-15 10:14 UTC, besscerule commented on test/controllers/CheckYourAnswersControllerSpec.scala
> +
remove line